import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { GSAP } from 'components/gsap'
import { RealViewport } from 'components/real-viewport'
import { Lenis } from 'components/lenis'
import Footer from 'components/footer'
import Navbar from 'components/navbar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <RealViewport />
        <Navbar />
        {children}
        <Footer />
        <Lenis root />
        <GSAP />
      </body>
    </html>
  )
}
